const skillIconAliases: Record<string, string> = {
	"c++": "cpp",
	"c#": "cs",
	css3: "css",
	"d3.js": "d3",
	javascript: "js",
	markdown: "md",
	"next.js": "nextjs",
	next: "nextjs",
	"node.js": "nodejs",
	node: "nodejs",
	postgresql: "postgres",
	python: "py",
	"react.js": "react",
	"react native": "react",
	reactjs: "react",
	"tailwind css": "tailwind",
	typescript: "ts",
	vuejs: "vue",
	"vue.js": "vue",
	"visual studio code": "vscode",
	vscode: "vscode",
};

const skillIconIds = new Set([
	"angular",
	"ansible",
	"apollo",
	"astro",
	"aws",
	"azure",
	"babel",
	"bash",
	"bitbucket",
	"blender",
	"bootstrap",
	"bun",
	"c",
	"cs",
	"cpp",
	"cassandra",
	"clojure",
	"cloudflare",
	"cmake",
	"coffeescript",
	"css",
	"cypress",
	"d3",
	"dart",
	"debian",
	"deno",
	"discord",
	"discordjs",
	"django",
	"docker",
	"dotnet",
	"dynamodb",
	"electron",
	"elixir",
	"ember",
	"express",
	"fastapi",
	"figma",
	"firebase",
	"flask",
	"flutter",
	"gatsby",
	"gcp",
	"git",
	"github",
	"githubactions",
	"gitlab",
	"go",
	"graphql",
	"gulp",
	"haskell",
	"html",
	"htmx",
	"java",
	"js",
	"jenkins",
	"jest",
	"jquery",
	"kafka",
	"kotlin",
	"kubernetes",
	"laravel",
	"latex",
	"less",
	"linux",
	"lua",
	"md",
	"materialui",
	"matlab",
	"mongodb",
	"mysql",
	"nestjs",
	"netlify",
	"nextjs",
	"nginx",
	"nodejs",
	"notion",
	"npm",
	"nuxtjs",
	"opencv",
	"p5js",
	"perl",
	"php",
	"pinia",
	"postgres",
	"postman",
	"powershell",
	"prisma",
	"prometheus",
	"pug",
	"pycharm",
	"py",
	"pytorch",
	"qt",
	"r",
	"rabbitmq",
	"rails",
	"raspberrypi",
	"react",
	"reactivex",
	"redis",
	"redux",
	"regex",
	"remix",
	"ruby",
	"rust",
	"sass",
	"spring",
	"sqlite",
	"stackoverflow",
	"styledcomponents",
	"supabase",
	"swift",
	"symfony",
	"tailwind",
	"tauri",
	"tensorflow",
	"terraform",
	"threejs",
	"ts",
	"ubuntu",
	"unity",
	"unreal",
	"vercel",
	"vim",
	"visualstudio",
	"vite",
	"vitest",
	"vscode",
	"vue",
	"vuetify",
	"wasm",
	"webpack",
	"webstorm",
	"windows",
	"wordpress",
	"yarn",
	"zig",
]);

const skillIconLabels: Record<string, string> = {
	c: "C",
	cs: "C#",
	cpp: "C++",
	d3: "D3.js",
	go: "Go",
	html: "HTML",
	js: "JavaScript",
	md: "Markdown",
	nodejs: "Node.js",
	nextjs: "Next.js",
	postgres: "PostgreSQL",
	py: "Python",
	react: "React",
	threejs: "Three.js",
	ts: "TypeScript",
	vscode: "VS Code",
	vue: "Vue",
};

export const skillIconSuggestions = [...skillIconIds].map((iconId) => ({
	id: iconId,
	label: skillIconLabels[iconId] ?? iconId.charAt(0).toUpperCase() + iconId.slice(1),
}));

function normalizeSkill(skill: string) {
	return skill.trim().toLowerCase().replace(/\s+/g, " ");
}

export function getSkillIconId(skill: string): string | undefined {
	const normalizedSkill = normalizeSkill(skill);
	const iconId = skillIconAliases[normalizedSkill] ?? normalizedSkill.replace(/[.\s-]/g, "");
	return skillIconIds.has(iconId) ? iconId : undefined;
}

export function getSkillIconUrl(skill: string): string | undefined {
	const iconId = getSkillIconId(skill);
	return iconId ? `https://skillicons.dev/icons?i=${iconId}&theme=light` : undefined;
}
